### ISSUE TITLE
Drone rpm build

### ISSUE THREAD

**Issue by gboddin** [iuscommunity/automation-examples#12]
Just sharing back ;)

https://github.com/ec-europa/ne-pipelines/blob/master/drone/fpfis-rpm-repo.yml
https://github.com/ec-europa/docker-fpfis/blob/release/mock-beta/Dockerfile

That's what we use to build and publish RPMs from drone

**Comment by b-harper** [comment]
Hey @gboddin,

Are those private repositories? I am getting 404s for both of them.

**Comment by gboddin** [comment]
Indeed , silly me :)

So it goes ( mock Dockerfile ) : 
```
FROM centos:7
RUN yum -y install mock spectool
RUN adduser -m -G mock build
COPY conf/fpfis-6-x86_64.cfg /etc/mock/fpfis-6-x86_64.cfg
COPY conf/fpfis-7-x86_64.cfg /etc/mock/fpfis-7-x86_64.cfg
USER build
ENTRYPOINT /usr/bin/mock
```

.drone.yml ( we use a single repo for our packages but it should be trivial to use the repo name instead )
```
matrix:
  DISTRO:
    - fpfis-6-x86_64
    - fpfis-7-x86_64
  PACKAGE:
    - ${DRONE_BRANCH##*/}

workspace:
  base: /mock
  path: build

pipeline:
  prepare-dir:
    image: alpine:latest
    commands:
      - mkdir -pm 777 RPMS SRPMS SOURCES/${PACKAGE}
      - chmod -R 777 SOURCES/${PACKAGE} RPMS SRPMS

  download-package:
    image: fpfis/mock-beta
    commands:
      - spectool -g -C /mock/build/SOURCES/${PACKAGE} /mock/build/SPECS/${PACKAGE}.spec

  build-srpm:
    image: fpfis/mock-beta
    privileged: true
    commands:
      - /usr/bin/mock -r ${DISTRO} --spec=SPECS/${PACKAGE}.spec --sources=/mock/build/SOURCES/${PACKAGE} --resultdir=/mock/build/SRPMS --buildsrpm

  built-rpm:
    image: fpfis/mock-beta
    privileged: true
    commands:
      - /usr/bin/mock --clean -r ${DISTRO} --resultdir=/mock/build/RPMS --rebuild /mock/build/SRPMS/$(ls -1utr SRPMS/|grep ^${PACKAGE}-.*src\.rpm$|head -1)

  show-result:
    image: alpine:latest
    when:
      status: [ success, failure ]
    commands:
      - ls -lha SRPMS RPMS
      - tail -200 SRPMS/*log
      - tail -200 RPMS/*log

  upload:
    image: drillster/drone-rsync
    secrets: [ PLUGIN_KEY, PLUGIN_HOSTS, PLUGIN_PORT ]
    user: rpm-incoming
    source: ./RPMS/*.rpm
    target: $${DISTRO}/
    when:
      event: push
      branch: release/*
```

Regards,
